#!/usr/bin/env python
# -*- coding: utf-8 -*-


class FilesystemError:

    ERROR_FILE_DOWNLOAD_CALLBACK_NOT_CALLABLE = ''
    ERROR_FILE_DOWNLOAD_ALREADY_EXISTS = ''
    ERROR_FILE_DOWNLOAD_UNHANDLED_EXCEPTION = ''

    ERROR_FILE_UPLOAD_UNHANDLED_EXCEPTION = ''
    ERROR_FILE_UPLOAD_CALLBACK_NOT_CALLABLE = ''
    ERROR_FILE_UPLOAD_ALREADY_EXISTS = ''

    ERROR_ITERATE_STRATEGY_UNKNOWN = ''
    ERROR_ITERATE_CALLBACK_NOT_CALLABLE = ''
